server:
  port: 8082

spring:
  application:
    name: restaurant
  data:
    mongodb:
      uri: mongodb://localhost:27017/restaurantdb
  web:
    resources:
        static-locations: classpath:/static/, file:uploads/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
